### ISSUE TITLE
Add documentation for RadAutoCompleteTextView CSS styling

### ISSUE THREAD

**Issue by bundyo** [NativeScript/docs-v7#1748]
### Please, tell us what's the problem?
- [ ] A typo
- [ ] Wrong documentation
- [ ] Improvement of existing article
- [x] Missing documentation
- [x] New article needed

### Please, tell us more details
Since 5.1.0, RadAutoCompleteTextView can be styled with CSS, we should provide documentation for that. This probably will result in 3 articles - one for each flavor. These are the supported properties:

```css
RadAutoCompleteTextView {
    color: ...;
    background: ...;
    padding: ...;
    margin: ...;
    border (width, color, radius)
    font (size, weight)
    enums (display-mode, completion-mode, etc.)
}

RadAutoCompleteTextView:focus {
    /* Same as above */
}

ClearButton {
	color: ...;
	background-image: ...;
}

SuggestionView {
	color: ...;
	background: ...;
	margin: ...;
	border (width, color, radius)
	font (size, weight)
}

Token {
	color: ...;
	background: ...;
	padding: ...;
	margin: ...;
	border (width, color, radius)
	font (size, weight)
}

Token:selected {
    /* Same as above */
}

TokenClearButton {
	color: ...;
	background-image: ...;
}
```
