### ISSUE TITLE
Chapter 4.5 - transitions

### ISSUE THREAD

**Issue by carrbrpoa** [NativeScript/docs-v7#757]
After implementing the suggested in [4.5](http://docs.nativescript.org/angular/tutorial/ng-chapter-4#45-activityindicator), the fade animation happens normally, but after that, the list disappears. Anything I miss?

Thanks

**Comment by carrbrpoa** [comment]
Well, seems that setting

```css
ListView {
  opacity: 1;
}
```

instead of 
```css
ListView {
  opacity: 0;
}
```

works; just not sure if it's right.
